In [1]:
import pandas as pd
import numpy as np

# aggregated_results is produced by gencsv.py, which read all SUMMARY_* files and parse them into one CSV
# aggregated_results_new.csv contains data for newly added target jerryscript, php, z3
data_path = "aggregated_results_undirected.csv"
data = pd.read_csv(data_path)
data.head()

,file,scenario,git_info,max_iter,LLM,LLM_temp,NOFEEDBACK,GENCMD,RUNFUZZ,subject,commit,final_result,unintended_bug,time,iid,score,success
0,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jerryscript,b7e3bae,N,False,160,5013,0,0
1,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jerryscript,70e275e,R,False,191,5138,1,0
2,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jerryscript,53b61c1,R,False,184,5117,1,0
3,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jerryscript,70e275e,R,False,205,5153,1,0
4,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jerryscript,b7e3bae,N,False,160,5013,0,0

In [2]:
# check the unique values in the column
for column in data.columns:
    if column in ["file", "time"]:
        continue
    print(f"{column}: {data[column].unique()}")

scenario: <StringArray>
['BIC', 'FIX']
Length: 2, dtype: str
git_info: <StringArray>
['NONE']
Length: 1, dtype: str
max_iter: [5]
LLM: <StringArray>
['gpt-4o-2024-08-06']
Length: 1, dtype: str
LLM_temp: [0.5]
NOFEEDBACK: [nan]
GENCMD: [nan]
RUNFUZZ: [nan]
subject: <StringArray>
['jerryscript',        'mujs',     'php-src',     'poppler',          'z3',
     'libxml2',          'jq', 'micropython']
Length: 8, dtype: str
commit: <StringArray>
['b7e3bae', '70e275e', '53b61c1', '3686410', '95cc5e9', 'd7e2125', 'de51531',
 '8c27b12', '832e069', '4c7f6be', '3f71a1c', '833f82c', '6871e5b', 'f93d245',
 '8b5ba20', '5cb38e9', '8c704ab', '998bce1', '7904a08', '18b18f0', 'd17ed34',
 'b068c2f', 'e4473ab', '3d35d20', '3cae777', 'e674ca6', 'aaf2e80', '245abad',
 '4564a00', 'efb6868', 'a4ca3a9', '907d05a', '1be35ee', '0f3c562', 'a62e4b2',
 'dec87fe', 'a7b1db6', 'a849a29', 'eea9c0b', '49610f5', 'a6b5027', '9a82b94',
 '74c84a8', '1406b20', '14604a4', '9cfc723', 'd0c3f01', '6273df6', 'db21cd5',
 '3ad7f81', 'dc6270d', '680baef', '0e067ef', '4003202', '3fa10e8', '71c2ab5',
 'de21386', '499c91b', '4c93955', '1fef566', '5e9189d', '69ead7d', 'e702046',
 '7e14680', 'f397a3e', '908ab1c', '3185bb5', 'c0252d7', '4b013ec', '0615d13']
Length: 70, dtype: str
final_result: <StringArray>
['N', 'R', 'X', 'D', 'B']
Length: 5, dtype: str
unintended_bug: [False  True]
iid: [ 5013  5138  5117  5153    65   141   145   166 16777 16978 17442 17463
  1282  1289  1303  1305  1381  6659  6914  7246  7252   535   550   553
   720   841  2825  2976  3262 49014 13007 13041 17733 17815 17841 17847]
score: [0 1 2 3]
success: [0 1]

In [3]:
# rows with final_result == 'B'
data_bug = data[data["final_result"] == "B"]
# keep only rows with different value in column 'commit'
data_bug = data_bug.drop_duplicates(subset=["iid"])
data_bug

,file,scenario,git_info,max_iter,LLM,LLM_temp,NOFEEDBACK,GENCMD,RUNFUZZ,subject,commit,final_result,unintended_bug,time,iid,score,success
210,SUMMARY_libxml2_BIC_GITNONE_ITER5_gpt-4o-2024-...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,libxml2,9a82b94,B,False,6,535,3,1
212,SUMMARY_libxml2_BIC_GITNONE_ITER5_gpt-4o-2024-...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,libxml2,1406b20,B,False,7,553,3,1
214,SUMMARY_libxml2_BIC_GITNONE_ITER5_gpt-4o-2024-...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,libxml2,9cfc723,B,False,5,841,3,1
262,SUMMARY_jq_BIC_GITNONE_ITER5_gpt-4o-2024-08-06...,BIC,NONE,5,gpt-4o-2024-08-06,0.5,NaN,NaN,NaN,jq,0e067ef,B,False,51,3262,3,1

In [ ]:
data_reach = data[data["final_result"] == "R"]
data_reach = data_reach.drop_duplicates(subset=["commit"])
# only display columns: file, iid, commit, final_result
data_reach = data_reach[["file", "iid", "commit", "final_result"]]
data_reach

,file,iid,commit,final_result
1,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,5138,70e275e,R
2,SUMMARY_jerryscript_BIC_GITNONE_ITER5_gpt-4o-2...,5117,53b61c1,R
26,SUMMARY_jerryscript_FIX_GITNONE_ITER5_gpt-4o-2...,5117,d7e2125,R
98,SUMMARY_php-src_BIC_GITNONE_ITER5_gpt-4o-2024-...,17442,998bce1,R
120,SUMMARY_poppler_BIC_GITNONE_ITER5_gpt-4o-2024-...,1282,3d35d20,R
121,SUMMARY_poppler_BIC_GITNONE_ITER5_gpt-4o-2024-...,1289,3cae777,R
145,SUMMARY_poppler_FIX_GITNONE_ITER5_gpt-4o-2024-...,1282,4564a00,R
261,SUMMARY_jq_BIC_GITNONE_ITER5_gpt-4o-2024-08-06...,2976,680baef,R
280,SUMMARY_jq_FIX_GITNONE_ITER5_gpt-4o-2024-08-06...,2825,3fa10e8,R
281,SUMMARY_jq_FIX_GITNONE_ITER5_gpt-4o-2024-08-06...,2976,71c2ab5,R
309,SUMMARY_micropython_BIC_GITNONE_ITER5_gpt-4o-2...,17815,69ead7d,R
312,SUMMARY_micropython_BIC_GITNONE_ITER5_gpt-4o-2...,13007,4c93955,R
333,SUMMARY_micropython_FIX_GITNONE_ITER5_gpt-4o-2...,17815,c0252d7,R
334,SUMMARY_micropython_FIX_GITNONE_ITER5_gpt-4o-2...,17841,4b013ec,R

In [5]:
data_behave = data[data["final_result"] == "D"]
data_behave = data_behave.drop_duplicates(subset=["commit"])
data_behave = data_behave[["file", "iid", "commit", "final_result"]]
data_behave

,file,iid,commit,final_result
114,SUMMARY_php-src_FIX_GITNONE_ITER5_gpt-4o-2024-...,17442,b068c2f,D
211,SUMMARY_libxml2_BIC_GITNONE_ITER5_gpt-4o-2024-...,550,74c84a8,D
213,SUMMARY_libxml2_BIC_GITNONE_ITER5_gpt-4o-2024-...,720,14604a4,D
238,SUMMARY_libxml2_FIX_GITNONE_ITER5_gpt-4o-2024-...,720,3ad7f81,D
310,SUMMARY_micropython_BIC_GITNONE_ITER5_gpt-4o-2...,17841,e702046,D